[workspace]
members = [
    "examples/container/capabilities",
    "examples/container/cpueater",
    "examples/container/crashing",
    "examples/container/datarw",
    "examples/container/memeater",
    "examples/container/resource/resource_hello",
    "examples/container/resource/ferris",
    "examples/container/seccomp",
    "libcap-sys",
    "minijail/rust/minijail",
    "minijail/rust/minijail-sys",
    "northstar",
    "northstar/hello_world",
    "northstar_tests",
    "northstar_tests/test_container",
    "npk",
    "nstar",
    "sextant",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z' # Optimize for size
