[workspace]

members = [
    "dcon",
    "examples/container/cpueater",
    "examples/container/crashing",
    "examples/container/datarw",
    "examples/container/hello",
    "examples/container/memeater",
    "examples/container/resource/ferris",
    "minijail/minijail",
    "minijail/minijail-sys",
    "north",
    "north_common",
    "sextant",
]

[profile.release]
lto = true

