[workspace]
members = [
    "examples/console",
    "examples/cpueater",
    "examples/crashing",
    "examples/ferris",
    "examples/hello-resource",
    "examples/hello-world",
    "examples/inspect",
    "examples/memeater",
    "examples/persistence",
    "examples/seccomp",
    "main",
    "northstar",
    "northstar-tests",
    "northstar-tests/test-container",
    "tools/nstar",
    "tools/schema",
    "tools/seccomp-util",
    "tools/sextant",
    "tools/stress",
]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
