[package]
name = "datarw"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2018"

[dependencies]
logd-logger = { git = "https://github.com/flxo/logd-logger.git" }
log = "0.4.8"
serde_json = "1.0.56"

[workspace]
