[package]
name = "cargo-npk"
version = "0.7.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.70"
atty = "0.2.14"
cargo-subcommand = { version = "0.11.0", features = ["clap"] }
cargo_metadata = "0.15.3"
clap = { version = "4.1.11", features = ["derive"] }
human_bytes = "0.4.1"
humantime = "2.1.0"
northstar-runtime = { version = "^0.7.1", path = "../northstar-runtime", features = ["npk"] }
serde = { version = "1.0.158", features = ["derive"] }
tempfile = "3.4.0"
termcolor = "1.2.0"
toml = "0.7.3"
