[package]
name = "northstar-client"
version = "0.7.2-pre"
authors = ["ESRLabs"]
description = "Northstar is an container runtime for Linux targetting embedded systems"
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/esrlabs/northstar"

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
futures = "0.3.27"
northstar-runtime = { version = "^0.7.2-pre", path = "../northstar-runtime", features = ["api"] }
thiserror = "1.0.40"
tokio = "1.26.0"

