[package]
name = "northstar-tests-derive"
version = "0.8.3-pre"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.26"
syn = { version = "2.0.16", features = ["full"] }
