[package]
name = "northstar-nstar"
version = "0.6.1-pre"
authors = ["ESRLabs"]
description = "Northstar is an container runtime for Linux targetting embedded systems"
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/esrlabs/northstar"

[dependencies]
anyhow = { version = "1.0.62", features = ["backtrace"] }
base64 = "0.13.0"
clap = { version = "3.2.17", features = ["derive"] }
clap_complete = "3.2.4"
futures = { version = "0.3.23", default-features = false }
humantime = "2.1.0"
itertools = "0.10.3"
northstar-client = { version = "^0.6.1-pre", path = "../northstar-client" }
northstar-runtime = { version = "^0.6.1-pre", path = "../northstar-runtime", features = ["seccomp"] }
pin-project-lite = "0.2.9"
prettytable-rs = "0.9.0"
regex = "1.6.0"
serde = "1.0.143"
serde_json = "1.0.83"
serde_yaml = "0.9.10"
tokio = { version = "1.20.1", features = ["fs", "io-std", "io-util", "macros", "net", "rt", "time"] }
tokio-util = "0.7.3"
url = "2.2.2"
