[package]
name = "cpueater"
version = "0.1.0"
authors = ["Felix Obenhuber <felix.obenhuber@esrlabs.com>"]
edition = "2018"

[dependencies]
logd-logger = { git = "https://github.com/flxo/logd-logger.git" }
log = "0.4.8"

[workspace]
