[package]
name = "northstar-sextant"
version = "0.6.0"
authors = ["ESRLabs"]
description = "Northstar is an container runtime for Linux targetting embedded systems"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/esrlabs/northstar"

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
base64 = "0.13.0"
clap = { version = "3.2.16", features = ["derive"] }
colored = "2.0.0"
ed25519-dalek = "1.0.1"
env_logger = "0.9.0"
log = "0.4.17"
northstar-runtime = { version = "^0.6.0", path = "../northstar-runtime", features = ["npk"] }
tempfile = "3.3.0"
zip = { version = "0.6.2", default-features = false }
