[package]
name = "northstar-sextant"
version = "0.8.3"
authors = ["ESRLabs"]
description = "Northstar is an container runtime for Linux targetting embedded systems"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/esrlabs/northstar"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
clap = { version = "4.2.7", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.10.0"
northstar-runtime = { version = "^0.8.3", path = "../northstar-runtime", features = ["npk"] }
tempfile = "3.5.0"
zip = { version = "0.6.6", default-features = false }
