[package]
name = "northstar-sextant"
version = "0.6.1-pre"
authors = ["ESRLabs"]
description = "Northstar is an container runtime for Linux targetting embedded systems"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/esrlabs/northstar"

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
base64 = "0.13.0"
clap = { version = "4.0.15", features = ["derive"] }
colored = "2.0.0"
ed25519-dalek = "1.0.1"
env_logger = "0.9.1"
log = "0.4.17"
northstar-runtime = { version = "^0.6.1-pre", path = "../northstar-runtime", features = ["npk"] }
tempfile = "3.3.0"
zip = { version = "0.6.3", default-features = false }
